package com.eltechs.axs.gamesControls;

import com.eltechs.axs.GestureStateMachine.GestureContext;
import com.eltechs.axs.GestureStateMachine.GestureState1FingerMeasureSpeed;
import com.eltechs.axs.GestureStateMachine.GestureState1FingerMoveToMouseDragAndDrop;
import com.eltechs.axs.GestureStateMachine.GestureState1FingerMoveToMouseMove;
import com.eltechs.axs.GestureStateMachine.GestureState1FingerMoveToScrollAsync;
import com.eltechs.axs.GestureStateMachine.GestureState1FingerToZoomMove;
import com.eltechs.axs.GestureStateMachine.GestureState2FingersToZoom;
import com.eltechs.axs.GestureStateMachine.GestureStateCheckFingerNearToPointer;
import com.eltechs.axs.GestureStateMachine.GestureStateCheckIfZoomed;
import com.eltechs.axs.GestureStateMachine.GestureStateClickToFingerFirstCoords;
import com.eltechs.axs.GestureStateMachine.GestureStateMouseWarpToFingerLastCoords;
import com.eltechs.axs.GestureStateMachine.GestureStateNeutral;
import com.eltechs.axs.GestureStateMachine.GestureStatePressKey;
import com.eltechs.axs.GestureStateMachine.GestureStateWaitFingersNumberChangeWithTimeout;
import com.eltechs.axs.GestureStateMachine.GestureStateWaitForNeutral;
import com.eltechs.axs.GestureStateMachine.PointerContext;
import com.eltechs.axs.GuestAppActionAdapters.AlignedMouseClickAdapter;
import com.eltechs.axs.GuestAppActionAdapters.AsyncScrollAdapterWithPointer;
import com.eltechs.axs.GuestAppActionAdapters.MouseClickAdapterWithCheckPlacementContext;
import com.eltechs.axs.GuestAppActionAdapters.MouseMoveAdapter;
import com.eltechs.axs.GuestAppActionAdapters.OffsetMouseMoveAdapter;
import com.eltechs.axs.GuestAppActionAdapters.PressAndHoldWithPauseMouseClickAdapter;
import com.eltechs.axs.GuestAppActionAdapters.PressAndReleaseMouseClickAdapter;
import com.eltechs.axs.GuestAppActionAdapters.PressAndReleaseWithModifierKeyMouseClickAdapter;
import com.eltechs.axs.GuestAppActionAdapters.SimpleDragAndDropAdapter;
import com.eltechs.axs.GuestAppActionAdapters.SimpleMouseMoveAdapter;
import com.eltechs.axs.GuestAppActionAdapters.SimpleMousePointAndClickAdapter;
import com.eltechs.axs.KeyCodesX;
import com.eltechs.axs.TouchArea;
import com.eltechs.axs.TouchEventMultiplexor;
import com.eltechs.axs.finiteStateMachine.FiniteStateMachine;
import com.eltechs.axs.finiteStateMachine.generalStates.FSMStateRunRunnable;
import com.eltechs.axs.geom.Rectangle;
import com.eltechs.axs.widgets.viewOfXServer.ViewOfXServer;

public class GestureMachineConfigurerArcanum {
    private static final float clickAlignThresholdInches = 0.3f;
    private static final float doubleClickMaxDistance = 0.15f;
    private static final int doubleClickMaxIntervalMs = 200;
    private static final float fingerAimingMaxMoveInches = 0.12f;
    private static final int fingerSpeedCheckTimeMs = 400;
    private static final float fingerStandingMaxMoveInches = 0.12f;
    private static final float fingerTapMaxMoveInches = 0.2f;
    private static final int fingerTapMaxTimeMs = 400;
    private static final int maxTapTimeMs = 300;
    private static final int mouseActionSleepMs = 50;
    private static final float pixelsInScrollUnitX = 0.5f;
    private static final float pixelsInScrollUnitY = 0.25f;
    private static final int pointerMarginXPixels = 50;
    private static final long scrollTimerPeriod = 350;

    public static GestureContext createGestureContext(ViewOfXServer viewOfXServer, TouchArea touchArea, TouchEventMultiplexor touchEventMultiplexor, int i, Runnable runnable) {
        ViewOfXServer viewOfXServer2 = viewOfXServer;
        GestureContext gestureContext = new GestureContext(viewOfXServer2, touchArea, touchEventMultiplexor);
        PointerContext pointerContext = new PointerContext();
        GestureStateNeutral gestureStateNeutral = new GestureStateNeutral(gestureContext);
        GestureStateWaitForNeutral gestureStateWaitForNeutral = new GestureStateWaitForNeutral(gestureContext);
        float f = (float) i;
        float f2 = 0.12f * f;
        GestureState1FingerMeasureSpeed gestureState1FingerMeasureSpeed = new GestureState1FingerMeasureSpeed(gestureContext, 400, f2, f2, fingerTapMaxMoveInches * f, 400.0f);
        GestureStateCheckIfZoomed gestureStateCheckIfZoomed = new GestureStateCheckIfZoomed(gestureContext);
        GestureStateMouseWarpToFingerLastCoords gestureStateMouseWarpToFingerLastCoords = new GestureStateMouseWarpToFingerLastCoords(gestureContext, new SimpleMouseMoveAdapter(gestureContext.getPointerReporter()), pointerContext);
        SimpleMousePointAndClickAdapter simpleMousePointAndClickAdapter = new SimpleMousePointAndClickAdapter(new SimpleMouseMoveAdapter(gestureContext.getPointerReporter()), new PressAndReleaseMouseClickAdapter(gestureContext.getPointerReporter(), 1, 50), pointerContext);
        SimpleMousePointAndClickAdapter simpleMousePointAndClickAdapter2 = simpleMousePointAndClickAdapter;
        float f3 = clickAlignThresholdInches * f;
        PointerContext pointerContext2 = pointerContext;
        AlignedMouseClickAdapter alignedMouseClickAdapter = new AlignedMouseClickAdapter(new SimpleMouseMoveAdapter(gestureContext.getPointerReporter()), new PressAndReleaseMouseClickAdapter(gestureContext.getPointerReporter(), 1, 50), new PressAndReleaseMouseClickAdapter(gestureContext.getPointerReporter(), 1, 50), viewOfXServer2, pointerContext2, f3);
        AlignedMouseClickAdapter alignedMouseClickAdapter2 = new AlignedMouseClickAdapter(new SimpleMouseMoveAdapter(gestureContext.getPointerReporter()), new PressAndReleaseMouseClickAdapter(gestureContext.getPointerReporter(), 1, 50), new PressAndReleaseMouseClickAdapter(gestureContext.getPointerReporter(), 1, 50), viewOfXServer2, pointerContext2, 0.15f * f);
        MouseClickAdapterWithCheckPlacementContext mouseClickAdapterWithCheckPlacementContext = new MouseClickAdapterWithCheckPlacementContext(simpleMousePointAndClickAdapter2, alignedMouseClickAdapter, alignedMouseClickAdapter2, pointerContext, 200);
        GestureStateClickToFingerFirstCoords gestureStateClickToFingerFirstCoords = new GestureStateClickToFingerFirstCoords(gestureContext, mouseClickAdapterWithCheckPlacementContext);
        GestureStateWaitFingersNumberChangeWithTimeout gestureStateWaitFingersNumberChangeWithTimeout = new GestureStateWaitFingersNumberChangeWithTimeout(gestureContext, maxTapTimeMs);
        GestureStateWaitFingersNumberChangeWithTimeout gestureStateWaitFingersNumberChangeWithTimeout2 = new GestureStateWaitFingersNumberChangeWithTimeout(gestureContext, maxTapTimeMs);
        FSMStateRunRunnable fSMStateRunRunnable = new FSMStateRunRunnable(runnable);
        GestureStatePressKey gestureStatePressKey = new GestureStatePressKey(gestureContext, KeyCodesX.KEY_SPACE);
        MouseMoveAdapter mouseMoveAdapter = MouseMoveAdapter.dummy;
        PressAndReleaseWithModifierKeyMouseClickAdapter pressAndReleaseWithModifierKeyMouseClickAdapter = new PressAndReleaseWithModifierKeyMouseClickAdapter(gestureContext.getPointerReporter(), 1, 50, gestureContext.getKeyboardReporter(), KeyCodesX.KEY_ALT_LEFT);
        GestureStateClickToFingerFirstCoords gestureStateClickToFingerFirstCoords2 = new GestureStateClickToFingerFirstCoords(gestureContext, new SimpleMousePointAndClickAdapter(mouseMoveAdapter, pressAndReleaseWithModifierKeyMouseClickAdapter, pointerContext));
        GestureStatePressKey gestureStatePressKey2 = gestureStatePressKey;
        FSMStateRunRunnable fSMStateRunRunnable2 = fSMStateRunRunnable;
        GestureStateClickToFingerFirstCoords gestureStateClickToFingerFirstCoords3 = gestureStateClickToFingerFirstCoords;
        GestureStateClickToFingerFirstCoords gestureStateClickToFingerFirstCoords4 = gestureStateClickToFingerFirstCoords2;
        GestureStatePressKey gestureStatePressKey3 = gestureStatePressKey2;
        FSMStateRunRunnable fSMStateRunRunnable3 = fSMStateRunRunnable2;
        GestureStateWaitFingersNumberChangeWithTimeout gestureStateWaitFingersNumberChangeWithTimeout3 = gestureStateWaitFingersNumberChangeWithTimeout2;
        GestureState1FingerMoveToMouseDragAndDrop gestureState1FingerMoveToMouseDragAndDrop = new GestureState1FingerMoveToMouseDragAndDrop(gestureContext, new SimpleDragAndDropAdapter(new SimpleMouseMoveAdapter(gestureContext.getPointerReporter()), new PressAndHoldWithPauseMouseClickAdapter(gestureContext.getPointerReporter(), 1, 50), new Runnable() {
            public void run() {
            }
        }), pointerContext, true, 0.0f);
        GestureState1FingerMoveToMouseDragAndDrop gestureState1FingerMoveToMouseDragAndDrop2 = gestureState1FingerMoveToMouseDragAndDrop;
        GestureStateWaitFingersNumberChangeWithTimeout gestureStateWaitFingersNumberChangeWithTimeout4 = gestureStateWaitFingersNumberChangeWithTimeout;
        GestureStateClickToFingerFirstCoords gestureStateClickToFingerFirstCoords5 = gestureStateClickToFingerFirstCoords3;
        GestureStateWaitForNeutral gestureStateWaitForNeutral2 = gestureStateWaitForNeutral;
        GestureStateCheckIfZoomed gestureStateCheckIfZoomed2 = gestureStateCheckIfZoomed;
        GestureStateMouseWarpToFingerLastCoords gestureStateMouseWarpToFingerLastCoords2 = gestureStateMouseWarpToFingerLastCoords;
        GestureState1FingerMoveToMouseDragAndDrop gestureState1FingerMoveToMouseDragAndDrop3 = gestureState1FingerMoveToMouseDragAndDrop2;
        GestureState1FingerMoveToScrollAsync gestureState1FingerMoveToScrollAsync = new GestureState1FingerMoveToScrollAsync(gestureContext, new AsyncScrollAdapterWithPointer(gestureContext.getViewFacade(), new Rectangle(0, 0, gestureContext.getViewFacade().getScreenInfo().widthInPixels, gestureContext.getViewFacade().getScreenInfo().heightInPixels)), 1000000.0f, 1000000.0f, f * 1.0f, true, 50, true);
        GestureState1FingerToZoomMove gestureState1FingerToZoomMove = new GestureState1FingerToZoomMove(gestureContext);
        GestureState2FingersToZoom gestureState2FingersToZoom = new GestureState2FingersToZoom(gestureContext);
        GestureStateCheckFingerNearToPointer gestureStateCheckFingerNearToPointer = new GestureStateCheckFingerNearToPointer(gestureContext, (double) f3, false);
        GestureState1FingerMoveToMouseMove gestureState1FingerMoveToMouseMove = new GestureState1FingerMoveToMouseMove(gestureContext, pointerContext, new OffsetMouseMoveAdapter(new SimpleMouseMoveAdapter(gestureContext.getPointerReporter()), 0.0f, f * -0.4f));
        FiniteStateMachine finiteStateMachine = new FiniteStateMachine();
        GestureStateClickToFingerFirstCoords gestureStateClickToFingerFirstCoords6 = gestureStateClickToFingerFirstCoords5;
        GestureStateWaitFingersNumberChangeWithTimeout gestureStateWaitFingersNumberChangeWithTimeout5 = gestureStateWaitFingersNumberChangeWithTimeout4;
        GestureStateWaitFingersNumberChangeWithTimeout gestureStateWaitFingersNumberChangeWithTimeout6 = gestureStateWaitFingersNumberChangeWithTimeout3;
        FSMStateRunRunnable fSMStateRunRunnable4 = fSMStateRunRunnable3;
        GestureStatePressKey gestureStatePressKey4 = gestureStatePressKey3;
        GestureContext gestureContext2 = gestureContext;
        GestureStateClickToFingerFirstCoords gestureStateClickToFingerFirstCoords7 = gestureStateClickToFingerFirstCoords4;
        FSMStateRunRunnable fSMStateRunRunnable5 = fSMStateRunRunnable4;
        GestureState1FingerMoveToMouseDragAndDrop gestureState1FingerMoveToMouseDragAndDrop4 = gestureState1FingerMoveToMouseDragAndDrop3;
        GestureStatePressKey gestureStatePressKey5 = gestureStatePressKey4;
        GestureState1FingerMoveToScrollAsync gestureState1FingerMoveToScrollAsync3 = gestureState1FingerMoveToScrollAsync;
        finiteStateMachine.setStatesList(gestureStateNeutral, gestureStateCheckFingerNearToPointer, gestureState1FingerMeasureSpeed, gestureStateMouseWarpToFingerLastCoords2, gestureStateClickToFingerFirstCoords6, gestureStateCheckIfZoomed2, gestureStateWaitFingersNumberChangeWithTimeout5, gestureStateWaitFingersNumberChangeWithTimeout6, fSMStateRunRunnable4, gestureStatePressKey4, gestureStateClickToFingerFirstCoords7, gestureState1FingerMoveToMouseMove, gestureState1FingerMoveToMouseDragAndDrop4, gestureState1FingerMoveToScrollAsync3, gestureState1FingerToZoomMove, gestureState2FingersToZoom, gestureStateWaitForNeutral2);
        GestureStateWaitForNeutral gestureStateWaitForNeutral3 = gestureStateWaitForNeutral2;
        finiteStateMachine.addTransition(gestureStateWaitForNeutral3, GestureStateWaitForNeutral.GESTURE_COMPLETED, gestureStateNeutral);
        finiteStateMachine.addTransition(gestureStateNeutral, GestureStateNeutral.FINGER_TOUCHED, gestureState1FingerMeasureSpeed);
        finiteStateMachine.addTransition(gestureState1FingerMeasureSpeed, GestureState1FingerMeasureSpeed.FINGER_STANDING, gestureState1FingerMoveToMouseDragAndDrop4);
        finiteStateMachine.addTransition(gestureState1FingerMeasureSpeed, GestureState1FingerMeasureSpeed.FINGER_WALKED, gestureState1FingerMoveToMouseDragAndDrop4);
        finiteStateMachine.addTransition(gestureState1FingerMeasureSpeed, GestureState1FingerMeasureSpeed.FINGER_FLASHED, gestureStateCheckFingerNearToPointer);
        finiteStateMachine.addTransition(gestureState1FingerMeasureSpeed, GestureState1FingerMeasureSpeed.FINGER_TOUCHED, gestureStateWaitFingersNumberChangeWithTimeout5);
        finiteStateMachine.addTransition(gestureState1FingerMeasureSpeed, GestureState1FingerMeasureSpeed.FINGER_TAPPED, gestureStateClickToFingerFirstCoords6);
        finiteStateMachine.addTransition(gestureState1FingerMeasureSpeed, GestureState1FingerMeasureSpeed.FINGER_WALKED_AND_GONE, gestureStateMouseWarpToFingerLastCoords2);
        GestureStateCheckIfZoomed gestureStateCheckIfZoomed3 = gestureStateCheckIfZoomed2;
        finiteStateMachine.addTransition(gestureStateCheckFingerNearToPointer, GestureStateCheckFingerNearToPointer.FAR, gestureStateCheckIfZoomed3);
        finiteStateMachine.addTransition(gestureStateCheckFingerNearToPointer, GestureStateCheckFingerNearToPointer.NEAR, gestureState1FingerMoveToMouseMove);
        finiteStateMachine.addTransition(gestureStateCheckIfZoomed3, GestureStateCheckIfZoomed.ZOOM_OFF, gestureState1FingerMoveToScrollAsync3);
        finiteStateMachine.addTransition(gestureStateCheckIfZoomed3, GestureStateCheckIfZoomed.ZOOM_ON, gestureState1FingerToZoomMove);
        finiteStateMachine.addTransition(gestureStateWaitFingersNumberChangeWithTimeout5, GestureStateWaitFingersNumberChangeWithTimeout.FINGER_TOUCHED, gestureStateWaitFingersNumberChangeWithTimeout6);
        finiteStateMachine.addTransition(gestureStateWaitFingersNumberChangeWithTimeout5, GestureStateWaitFingersNumberChangeWithTimeout.FINGER_RELEASED, gestureStateClickToFingerFirstCoords7);
        finiteStateMachine.addTransition(gestureStateWaitFingersNumberChangeWithTimeout5, GestureStateWaitFingersNumberChangeWithTimeout.TIMED_OUT, gestureState2FingersToZoom);
        GestureStatePressKey gestureStatePressKey6 = gestureStatePressKey5;
        finiteStateMachine.addTransition(gestureStateWaitFingersNumberChangeWithTimeout6, GestureStateWaitFingersNumberChangeWithTimeout.FINGER_RELEASED, gestureStatePressKey6);
        finiteStateMachine.addTransition(gestureStateWaitFingersNumberChangeWithTimeout6, GestureStateWaitFingersNumberChangeWithTimeout.TIMED_OUT, gestureStatePressKey6);
        finiteStateMachine.addTransition(gestureStateWaitFingersNumberChangeWithTimeout6, GestureStateWaitFingersNumberChangeWithTimeout.FINGER_TOUCHED, fSMStateRunRunnable5);
        finiteStateMachine.addTransition(gestureState2FingersToZoom, GestureState2FingersToZoom.FINGER_RELEASED, gestureState1FingerToZoomMove);
        finiteStateMachine.addTransition(gestureState1FingerToZoomMove, GestureState1FingerToZoomMove.FINGER_TOUCHED, gestureState2FingersToZoom);
        finiteStateMachine.setInitialState(gestureStateNeutral);
        finiteStateMachine.setDefaultState(gestureStateWaitForNeutral3);
        finiteStateMachine.configurationCompleted();
        GestureContext gestureContext3 = gestureContext2;
        gestureContext3.setMachine(finiteStateMachine);
        return gestureContext3;
    }
}
